#单节点
spring:
  application:
    name: eureka
eureka:
  client:
    register-with-eureka: false # 不向注册中心注册自己，默认值是true
    fetch-registry: false # 不从注册中心获取注册的服务信息，默认值是true
    service-url:
      defaultZone: http://localhost:7900/eureka # 配置eureka server地址，用于注册服务和获取服务
  server:
    #关闭自我保护
    enable-self-preservation: false # 控制控制台会弹出红色警告语句
    #清理间隔时间
    eviction-interval-timer-in-ms: 5000
logging:
  level:
    root: info
server:
  port: 7900